# Author:https://github.com/Repcz
# TG:https://t.me/QVQ_Channel
#
# 官方文档：https://github.com/MetaCubeX/mihomo/blob/Meta/docs/config.yaml
#
# 以 '#' 或 '//' 开头的配置文件行为注释行
#
# Mihomo Version ≥ 1.8.4
#
# 最后更新时间: 2025-02-27 23:00
#
# ================

mixed-port: 65222 # HTTP(S) 和 SOCKS 代理混合端口
tcp-concurrent: true # TCP 并发连接所有 IP, 将使用最快握手的 TCP
allow-lan: false # 允许局域网连接
ipv6: true # 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
log-level: info # 日志等级 silent/error/warning/info/debug

hosts:
  "localhost": 127.0.0.1

dns:
  enable: true
  listen: :65223 # 开启 DNS 服务器监听
  ipv6: true # false 将返回 AAAA 的空结果
  use-hosts: true # 查询 hosts
  enhanced-mode: redir-host
  nameserver: [8.8.4.4, 1.1.1.1]

rules:
  - MATCH,DIRECT

listeners: #搭建代理节点

  - name: SS2022
    type: shadowsocks
    port: 65112
    listen: "::"
    cipher: 2022-blake3-aes-256-gcm # 2022-blake3-aes-128-gcm/2022-blake3-aes-256-gcm/2022-blake3-chacha20-poly1305
    password: SaAj4IC+cHEyWoCaUXeNBE+A8DcqKRsOELe4FOuuNJE= # openssl rand --base64 32
    udp: true
    udp-over-tcp: false
    ip-version: ipv4-prefer

    smux:
      enabled: true
      protocol: h2mux
      max-connections: 0
      min-streams: 0
      max-streams: 1
      statistic: true
      only-tcp: false
      padding: true