// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/show/v1/mixture.proto" (package "bilibili.app.show.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * 分区页的一个内容分组。
 *
 * @generated from protobuf message bilibili.app.show.v1.RegionContent
 */
export interface RegionContent {
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * @generated from protobuf field: repeated bilibili.app.show.v1.RegionIcon icons = 2
     */
    icons: RegionIcon[];
}
/**
 * 分区或快捷访问入口。
 *
 * @generated from protobuf message bilibili.app.show.v1.RegionIcon
 */
export interface RegionIcon {
    /**
     * @generated from protobuf field: string img = 1
     */
    img: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string url = 3
     */
    url: string;
    /**
     * @generated from protobuf field: int64 unique_id = 4
     */
    uniqueId: string;
    /**
     * @generated from protobuf field: int64 rid = 5
     */
    rid: string;
}
/**
 * 获取分区页数据响应。
 *
 * @generated from protobuf message bilibili.app.show.v1.RegionListReply
 */
export interface RegionListReply {
    /**
     * @generated from protobuf field: bilibili.app.show.v1.RegionContent shortcut = 1
     */
    shortcut?: RegionContent;
    /**
     * @generated from protobuf field: repeated bilibili.app.show.v1.RegionContent contents = 2
     */
    contents: RegionContent[];
}
/**
 * 保存快捷访问请求。
 *
 * @generated from protobuf message bilibili.app.show.v1.RegionShortcutReq
 */
export interface RegionShortcutReq {
    /**
     * @generated from protobuf field: repeated int64 unique_id = 1
     */
    uniqueId: string[];
}
declare class RegionContent$Type extends MessageType<RegionContent> {
    constructor();
    create(value?: PartialMessage<RegionContent>): RegionContent;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegionContent): RegionContent;
    internalBinaryWrite(message: RegionContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.show.v1.RegionContent
 */
export declare const RegionContent: RegionContent$Type;
declare class RegionIcon$Type extends MessageType<RegionIcon> {
    constructor();
    create(value?: PartialMessage<RegionIcon>): RegionIcon;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegionIcon): RegionIcon;
    internalBinaryWrite(message: RegionIcon, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.show.v1.RegionIcon
 */
export declare const RegionIcon: RegionIcon$Type;
declare class RegionListReply$Type extends MessageType<RegionListReply> {
    constructor();
    create(value?: PartialMessage<RegionListReply>): RegionListReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegionListReply): RegionListReply;
    internalBinaryWrite(message: RegionListReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.show.v1.RegionListReply
 */
export declare const RegionListReply: RegionListReply$Type;
declare class RegionShortcutReq$Type extends MessageType<RegionShortcutReq> {
    constructor();
    create(value?: PartialMessage<RegionShortcutReq>): RegionShortcutReq;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegionShortcutReq): RegionShortcutReq;
    internalBinaryWrite(message: RegionShortcutReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.show.v1.RegionShortcutReq
 */
export declare const RegionShortcutReq: RegionShortcutReq$Type;
export {};
