// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/show/v1/mixture.proto" (package "bilibili.app.show.v1", syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class RegionContent$Type extends MessageType {
    constructor() {
        super("bilibili.app.show.v1.RegionContent", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "icons", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => RegionIcon }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.title = "";
        message.icons = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* repeated bilibili.app.show.v1.RegionIcon icons */ 2:
                    message.icons.push(RegionIcon.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* repeated bilibili.app.show.v1.RegionIcon icons = 2; */
        for (let i = 0; i < message.icons.length; i++)
            RegionIcon.internalBinaryWrite(message.icons[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.show.v1.RegionContent
 */
export const RegionContent = new RegionContent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegionIcon$Type extends MessageType {
    constructor() {
        super("bilibili.app.show.v1.RegionIcon", [
            { no: 1, name: "img", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "unique_id", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "rid", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.img = "";
        message.title = "";
        message.url = "";
        message.uniqueId = "0";
        message.rid = "0";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string img */ 1:
                    message.img = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string url */ 3:
                    message.url = reader.string();
                    break;
                case /* int64 unique_id */ 4:
                    message.uniqueId = reader.int64().toString();
                    break;
                case /* int64 rid */ 5:
                    message.rid = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string img = 1; */
        if (message.img !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.img);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string url = 3; */
        if (message.url !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.url);
        /* int64 unique_id = 4; */
        if (message.uniqueId !== "0")
            writer.tag(4, WireType.Varint).int64(message.uniqueId);
        /* int64 rid = 5; */
        if (message.rid !== "0")
            writer.tag(5, WireType.Varint).int64(message.rid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.show.v1.RegionIcon
 */
export const RegionIcon = new RegionIcon$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegionListReply$Type extends MessageType {
    constructor() {
        super("bilibili.app.show.v1.RegionListReply", [
            { no: 1, name: "shortcut", kind: "message", T: () => RegionContent },
            { no: 2, name: "contents", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => RegionContent }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.contents = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bilibili.app.show.v1.RegionContent shortcut */ 1:
                    message.shortcut = RegionContent.internalBinaryRead(reader, reader.uint32(), options, message.shortcut);
                    break;
                case /* repeated bilibili.app.show.v1.RegionContent contents */ 2:
                    message.contents.push(RegionContent.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bilibili.app.show.v1.RegionContent shortcut = 1; */
        if (message.shortcut)
            RegionContent.internalBinaryWrite(message.shortcut, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated bilibili.app.show.v1.RegionContent contents = 2; */
        for (let i = 0; i < message.contents.length; i++)
            RegionContent.internalBinaryWrite(message.contents[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.show.v1.RegionListReply
 */
export const RegionListReply = new RegionListReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegionShortcutReq$Type extends MessageType {
    constructor() {
        super("bilibili.app.show.v1.RegionShortcutReq", [
            { no: 1, name: "unique_id", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.uniqueId = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated int64 unique_id */ 1:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.uniqueId.push(reader.int64().toString());
                    else
                        message.uniqueId.push(reader.int64().toString());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated int64 unique_id = 1; */
        if (message.uniqueId.length) {
            writer.tag(1, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.uniqueId.length; i++)
                writer.int64(message.uniqueId[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.show.v1.RegionShortcutReq
 */
export const RegionShortcutReq = new RegionShortcutReq$Type();
